config/routes.rb
Rails.application.routes.draw do
  root to: 'blogs#index'
  resources :blogs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index    
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)

    if @blog.save
      redirect_to blogs_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])

    if @blog.update(blog_params)
      redirect_to blogs_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def blog_params
      params.require(:blog).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blogs/edit.html.erb
<h1>Add new Blog</h1>
<%= form_with model: @blog do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %><br>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/index.html.erb
<h1>Blogs</h1>
<ul>
  <% @blogs.each do |blog| %>
    <li>
      Title = <%= link_to blog.name, blog %> , 
      Description = <%= link_to blog.description, blog %> <br>          
      <%= link_to "Edit", edit_blog_path(blog) %> /
      <%= link_to "Destroy", blog_path(blog), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
    </li>
      
   
  <% end %>
</ul>


<%= link_to "create new blog", new_blog_path %>

app/views/blogs/new.html.erb
<h1>Add new Blog</h1>
<%= form_with model: @blog do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %><br>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/show.html.erb
<h1><%= @blog.name %></h1>

<p><%= @blog.description %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>